#!/bin/bash

LATEST_RELEASE="0.17.2.3"

upgradeDistr() {
	sudo apt update
	sudo apt upgrade -y
	sudo apt autoclean
	sudo apt autoremove
}

checkPrevInstall() {
	if [ -f $HOME/vqr-cli  ]; then
		version=$($HOME/./vqr-cli --version)
		curr_ver=${version: -8}
		if [ "$curr_ver" != "$LATEST_RELEASE" ]; then
			echo Update to latest version ...
			$HOME/./vqr-cli stop
			sleep 2
			installLatestRelease
		else
			echo You have latest version "$curr_ver"
			exit
		fi
	else
		echo Install latest version
		sudo apt install wget
		installLatestRelease
	fi
}

installLatestRelease() {
	github_url="https://github.com/vovanchik-net/vqr/releases/download/"$LATEST_RELEASE
	github_tar="vqr-$LATEST_RELEASE-x86_64-linux-gnu.tar.gz"
	wget "$github_url""/""$github_tar"
	tar -xvf "$github_tar" -C $HOME/
	rm "$github_tar"
	$HOME/./vqrd -daemon
	sleep 2
	$HOME/./vqr-cli --version
}

installTelegramSend() {
	sudo chmod +x $HOME/vqr-manager/telegram-send
	$HOME/vqr-manager/./telegram-send "TelegramSend Done!"
}

installAutoSendFunds() {
        sudo apt install jq
	sudo chmod +x $HOME/vqr-manager/send-funds
	# Del previous & Add script to crontab (Run every 1 hour)
	crontab -l | grep -v "$HOME/vqr-manager/./send-funds >/dev/null 2>&1" | crontab
	crontab -l | { cat; echo "0 * * * * $HOME/vqr-manager/./send-funds >/dev/null 2>&1"; } | crontab
	# Send test message to Telegram
	# $HOME/vqr-manager/./telegram-send "AutoSendFunds Done!"
}
