#!/bin/bash

STACK="400"
AMOUNT="20"
SEND_TO=""

$HOME/./vqr-cli help > /dev/null 2>&1
if [ $? == "1" ]; then
  $HOME/./vqrd -daemon
  ip=$(curl https://ipinfo.io/ip > /dev/null 2>&1)
  $HOME/vqr-manager/./telegram-send "Перезапуск демона: "$ip
  sleep 2
 fi

validate=$($HOME/./vqr-cli validateaddress $SEND_TO | jq '.isvalid')
if [ "$validate" != "true" ]
  echo "Invalid : "$SEND_TO
  $HOME/vqr-manager/./telegram-send "Invalid : "$SEND_TO
fi

get_balance=$($HOME/./vqr-cli getbalance)
balance=$((${get_balance%%.*} - $STACK))
if [ "$balance" -gt $AMOUNT ]; then
  tx=$($HOME/./vqr-cli sendtoaddress $SEND_TO $AMOUNT)
  $HOME/vqr-manager/./telegram-send "https://vqr.vovanchik.net/tx.php?hash="$tx
fi
