#!/bin/bash

STACK="400"
AMOUNT="20"
SEND_TO=""

get_balance=$(./vqr-cli getbalance)
balance=$((${get_balance%.*} - $STACK))
if [ $balance \> $AMOUNT ]; then
  tx=$(./vqr-cli "$SEND_TO" $AMOUNT)
  telegram-send "https://vqr.vovanchik.net/tx.php?hash=$tx"
  else
    #telegram-send $balance
    exit
fi