#!/bin/bash

# script for sending TEXT/FILE to Telegram
# Usage: bash telegram-send "<text>" or "</path/to/file>" ..."folder
# non-exist" errors may be ignored
#
SEND_ME=$1
TG_BOT_ID=""
TG_CHAT_ID=""
#
# sending text-message
curl --socks5-basic \
-X POST https://api.telegram.org/bot"$TG_BOT_ID"/sendMessage \
-d chat_id="$TG_CHAT_ID" -d text="$SEND_ME"
#
# sending file-message
#cat "$SEND_ME" > /tmp/tg-send && \
#curl --socks5-basic \
#-s -X POST https://api.telegram.org/bot"$TG_BOT_ID"/sendDocument \
#-F chat_id="$TG_CHAT_ID" -F document=@/tmp/tg-send
#
# cleaning
#rm -f /tmp/tg-send